# Use Python image
FROM python:3.9

# Set working directory inside the container
WORKDIR /app

# Copy everything to /app
COPY app/ /app/

# Install Flask
RUN pip install flask

# Expose port 5000
EXPOSE 5000

ENV FLASK_ENV=development
ENV FLASK_APP=app.py

# Run the app
CMD ["python", "app.py"]



